# .github/workflows/norminette.yml
name: norminette
on: [push, pull_request]

jobs:
  check_norm:
    runs-on: ubuntu-latest
    name: norminette v2
    steps:
    - uses: actions/checkout@v2
    - name: Check norm in srcs
      uses: alexandregv/norminette-action@v2
      with:
        flags: 'srcs'
    - name: Check norm in includes
      uses: alexandregv/norminette-action@v2
      with:
        flags: 'includes'
